"""
Django settings for videocaller project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import dotenv
import dj_database_url

dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts.split(',') if host.strip()]

# Add Render.com domains automatically in production
if not DEBUG:
    # Auto-add *.onrender.com and *.onrender.io for Render deployments
    render_domains = ['onrender.com', 'onrender.io']
    current_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
    if current_host and current_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(current_host)

# Trust Render.com proxy headers
if not DEBUG:
    CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS if host not in ['localhost', '127.0.0.1']]
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Authentication redirects
LOGIN_REDIRECT_URL = 'home'  # Redirect to home page after login
LOGOUT_REDIRECT_URL = 'login'  # Redirect to login after logout
LOGIN_URL = 'login'  # Where to redirect for @login_required

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_q',

    # Your agora app comes here
    'agora'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'videocaller.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'videocaller.wsgi.application'
ASGI_APPLICATION = 'videocaller.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Use PostgreSQL on production (Render), SQLite for local dev
database_url = os.environ.get('DATABASE_URL', '').strip()
if database_url:
    DATABASES = {
        'default': dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for serving static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# AWS S3 Configuration
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')

# Agora Cloud Recording Configuration
AGORA_APP_ID = os.environ.get('AGORA_APP_ID')
AGORA_APP_CERTIFICATE = os.environ.get('AGORA_APP_CERTIFICATE')
AGORA_CUSTOMER_ID = os.environ.get('AGORA_CUSTOMER_ID')
AGORA_CUSTOMER_SECRET = os.environ.get('AGORA_CUSTOMER_SECRET')
AGORA_RECORDING_REGION = os.environ.get('AGORA_RECORDING_REGION', 'NA')

# AssemblyAI Configuration
ASSEMBLYAI_API_KEY = os.environ.get('ASSEMBLYAI_API_KEY')

# Google Gemini Configuration for RAG
GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY')
GOOGLE_EMBEDDING_MODEL = os.environ.get('GOOGLE_EMBEDDING_MODEL', 'models/embedding-001')
GOOGLE_EMBEDDING_DIMENSION = int(os.environ.get('GOOGLE_EMBEDDING_DIMENSION', 768))
GOOGLE_LLM_MODEL = os.environ.get('GOOGLE_LLM_MODEL', 'gemini-pro')
GOOGLE_GENERATE_MODEL = os.environ.get('GOOGLE_GENERATE_MODEL', 'gemini-2.5-flash-lite')
GOOGLE_CONNECT_TIMEOUT = int(os.environ.get('GOOGLE_CONNECT_TIMEOUT', 10))
GOOGLE_READ_TIMEOUT = int(os.environ.get('GOOGLE_READ_TIMEOUT', 600))
GOOGLE_MAX_TOKENS = int(os.environ.get('GOOGLE_MAX_TOKENS', 1000))

# Ollama Configuration for RAG
def _get_bool_env(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}

OLLAMA_URL = os.environ.get('OLLAMA_URL', 'http://localhost:11434')
OLLAMA_MODEL = os.environ.get('OLLAMA_MODEL', 'mistral')
OLLAMA_CONNECT_TIMEOUT = int(os.environ.get('OLLAMA_CONNECT_TIMEOUT', 10))
OLLAMA_READ_TIMEOUT = int(os.environ.get('OLLAMA_READ_TIMEOUT', 600))
OLLAMA_NUM_PREDICT = int(os.environ.get('OLLAMA_NUM_PREDICT', 1024))
OLLAMA_STREAM = _get_bool_env('OLLAMA_STREAM', True)

# Hugging Face Embeddings
HF_EMBEDDING_MODEL = os.environ.get('HF_EMBEDDING_MODEL', 'sentence-transformers/all-MiniLM-L6-v2')
HF_EMBEDDING_DIMENSION = int(os.environ.get('HF_EMBEDDING_DIMENSION', 384))

# Qdrant Vector Database Configuration
QDRANT_URL = os.environ.get('QDRANT_URL', 'http://localhost:6333')
QDRANT_API_KEY = os.environ.get('QDRANT_API_KEY')
QDRANT_COLLECTION_NAME = os.environ.get('QDRANT_COLLECTION_NAME', 'meeting_transcripts')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django-Q configuration
from urllib.parse import urlparse

redis_url = os.environ.get('REDIS_URL')
redis_config = None
if redis_url:
    parsed = urlparse(redis_url)
    # Render Redis URLs use rediss:// (SSL)
    redis_config = {
        'host': parsed.hostname,
        'port': parsed.port or 6379,
        'db': int((parsed.path or '/0').lstrip('/') or 0),
        'password': parsed.password,
        'ssl': parsed.scheme == 'rediss',
        'ssl_cert_reqs': None if parsed.scheme == 'rediss' else False
    }

Q_CLUSTER = {
    'name': 'videocaller',
    'workers': 2,
    'recycle': 500,
    'timeout': 1200,
    'retry': 1300,
    'queue_limit': 50,
    'bulk': 5,
    'orm': 'default',
    'redis': redis_config or {
        'host': os.environ.get('REDIS_HOST', '127.0.0.1'),
        'port': int(os.environ.get('REDIS_PORT', 6379)),
        'db': int(os.environ.get('REDIS_DB', 0)),
    }
}
