# Generated by Django 4.1.5 on 2026-02-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='recording_duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='recording_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='recording_file',
            field=models.FileField(blank=True, null=True, upload_to='recordings/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='transcript_file',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/%Y/%m/%d/'),
        ),
    ]
