# Generated by Django 4.1.5 on 2026-02-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0002_meetingroom_recording_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroom',
            name='recording_file',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='transcript_file',
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='recording_resource_id',
            field=models.CharField(blank=True, help_text='Agora Resource ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='recording_sid',
            field=models.CharField(blank=True, help_text='Agora Recording SID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='recording_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('recording', 'Recording'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=50),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='recording_uid',
            field=models.IntegerField(blank=True, help_text='Agora Recording Bot UID', null=True),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='s3_recording_url',
            field=models.URLField(blank=True, help_text='S3 URL for recording', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='s3_transcript_url',
            field=models.URLField(blank=True, help_text='S3 URL for transcript', max_length=500, null=True),
        ),
    ]
