# Generated by Django 4.1.5 on 2026-02-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0004_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='transcript_id',
            field=models.CharField(blank=True, help_text='AssemblyAI Transcript ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='transcript_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=50),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='transcript_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
