# Generated by Django 4.1.5 on 2026-02-03 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agora', '0005_meetingroom_transcript_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='chunks_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when chunks were created', null=True),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='embedding_version',
            field=models.IntegerField(default=1, help_text='Version of embeddings (for migration)'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='embeddings_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when embeddings were generated', null=True),
        ),
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField(help_text='Text chunk from transcript')),
                ('chunk_index', models.IntegerField(help_text='Order of chunk in transcript')),
                ('start_time', models.IntegerField(blank=True, help_text='Start time in seconds', null=True)),
                ('end_time', models.IntegerField(blank=True, help_text='End time in seconds', null=True)),
                ('embedding_vector_id', models.CharField(blank=True, help_text='Vector DB ID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_chunks', to='agora.meetingroom')),
            ],
            options={
                'ordering': ['meeting', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.TextField()),
                ('assistant_response', models.TextField()),
                ('relevant_chunks', models.JSONField(default=list, help_text='List of chunk IDs used for response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_history', to='agora.meetingroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
