# Generated by Django 4.1.5 on 2026-02-08 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agora', '0006_meetingroom_chunks_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(help_text='File extension or MIME hint', max_length=50)),
                ('s3_url', models.URLField(blank=True, max_length=500, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('embeddings_created_at', models.DateTimeField(blank=True, null=True)),
                ('embedding_version', models.IntegerField(default=1, help_text='Version of embeddings (for migration)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_uploads', to='agora.meetingroom')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField(help_text='Text chunk from document')),
                ('chunk_index', models.IntegerField(help_text='Order of chunk in document')),
                ('block_type', models.CharField(default='text', help_text='text/table/image/other', max_length=50)),
                ('metadata', models.JSONField(default=dict, help_text='Extractor metadata')),
                ('embedding_vector_id', models.CharField(blank=True, help_text='Vector DB ID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='agora.documentupload')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
    ]
