# Generated by Django 4.1.5 on 2026-02-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0007_document_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='storage_path',
            field=models.CharField(default='', help_text='Storage path for local processing', max_length=500),
            preserve_default=False,
        ),
    ]
