# Generated by Django 4.1.5 on 2026-02-10 00:00

from django.db import migrations, models
import django.db.models.deletion


def migrate_meeting_fields(apps, schema_editor):
    MeetingRoom = apps.get_model('agora', 'MeetingRoom')
    MeetingRecording = apps.get_model('agora', 'MeetingRecording')
    MeetingTranscript = apps.get_model('agora', 'MeetingTranscript')
    MeetingRagState = apps.get_model('agora', 'MeetingRagState')

    for room in MeetingRoom.objects.all():
        MeetingRecording.objects.create(
            meeting=room,
            recording_enabled=room.recording_enabled,
            recording_sid=room.recording_sid,
            recording_resource_id=room.recording_resource_id,
            recording_uid=room.recording_uid,
            recording_status=room.recording_status,
            s3_recording_url=room.s3_recording_url,
            recording_duration=room.recording_duration
        )
        MeetingTranscript.objects.create(
            meeting=room,
            transcript_text=room.transcript_text,
            transcript_status=room.transcript_status,
            transcript_id=room.transcript_id,
            s3_transcript_url=room.s3_transcript_url
        )
        MeetingRagState.objects.create(
            meeting=room,
            chunks_created_at=room.chunks_created_at,
            embeddings_created_at=room.embeddings_created_at,
            embedding_version=room.embedding_version
        )


def reverse_migrate_meeting_fields(apps, schema_editor):
    MeetingRoom = apps.get_model('agora', 'MeetingRoom')
    MeetingRecording = apps.get_model('agora', 'MeetingRecording')
    MeetingTranscript = apps.get_model('agora', 'MeetingTranscript')
    MeetingRagState = apps.get_model('agora', 'MeetingRagState')

    for room in MeetingRoom.objects.all():
        try:
            recording = MeetingRecording.objects.get(meeting=room)
            room.recording_enabled = recording.recording_enabled
            room.recording_sid = recording.recording_sid
            room.recording_resource_id = recording.recording_resource_id
            room.recording_uid = recording.recording_uid
            room.recording_status = recording.recording_status
            room.s3_recording_url = recording.s3_recording_url
            room.recording_duration = recording.recording_duration
        except MeetingRecording.DoesNotExist:
            pass

        try:
            transcript = MeetingTranscript.objects.get(meeting=room)
            room.transcript_text = transcript.transcript_text
            room.transcript_status = transcript.transcript_status
            room.transcript_id = transcript.transcript_id
            room.s3_transcript_url = transcript.s3_transcript_url
        except MeetingTranscript.DoesNotExist:
            pass

        try:
            rag_state = MeetingRagState.objects.get(meeting=room)
            room.chunks_created_at = rag_state.chunks_created_at
            room.embeddings_created_at = rag_state.embeddings_created_at
            room.embedding_version = rag_state.embedding_version
        except MeetingRagState.DoesNotExist:
            pass

        room.save()


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0008_document_upload_storage_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_enabled', models.BooleanField(default=False)),
                ('recording_sid', models.CharField(blank=True, help_text='Agora Recording SID', max_length=255, null=True)),
                ('recording_resource_id', models.CharField(blank=True, help_text='Agora Resource ID', max_length=255, null=True)),
                ('recording_uid', models.IntegerField(blank=True, help_text='Agora Recording Bot UID', null=True)),
                ('recording_status', models.CharField(choices=[('not_started', 'Not Started'), ('recording', 'Recording'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=50)),
                ('s3_recording_url', models.URLField(blank=True, help_text='S3 URL for recording', max_length=500, null=True)),
                ('recording_duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='agora.meetingroom')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('transcript_status', models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=50)),
                ('transcript_id', models.CharField(blank=True, help_text='AssemblyAI Transcript ID', max_length=255, null=True)),
                ('s3_transcript_url', models.URLField(blank=True, help_text='S3 URL for transcript', max_length=500, null=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='agora.meetingroom')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRagState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunks_created_at', models.DateTimeField(blank=True, help_text='Timestamp when chunks were created', null=True)),
                ('embeddings_created_at', models.DateTimeField(blank=True, help_text='Timestamp when embeddings were generated', null=True)),
                ('embedding_version', models.IntegerField(default=1, help_text='Version of embeddings (for migration)')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rag_state', to='agora.meetingroom')),
            ],
        ),
        migrations.RunPython(migrate_meeting_fields, reverse_migrate_meeting_fields),
        migrations.RemoveField(model_name='meetingroom', name='recording_enabled'),
        migrations.RemoveField(model_name='meetingroom', name='recording_sid'),
        migrations.RemoveField(model_name='meetingroom', name='recording_resource_id'),
        migrations.RemoveField(model_name='meetingroom', name='recording_uid'),
        migrations.RemoveField(model_name='meetingroom', name='recording_status'),
        migrations.RemoveField(model_name='meetingroom', name='s3_recording_url'),
        migrations.RemoveField(model_name='meetingroom', name='s3_transcript_url'),
        migrations.RemoveField(model_name='meetingroom', name='recording_duration'),
        migrations.RemoveField(model_name='meetingroom', name='transcript_text'),
        migrations.RemoveField(model_name='meetingroom', name='transcript_status'),
        migrations.RemoveField(model_name='meetingroom', name='transcript_id'),
        migrations.RemoveField(model_name='meetingroom', name='chunks_created_at'),
        migrations.RemoveField(model_name='meetingroom', name='embeddings_created_at'),
        migrations.RemoveField(model_name='meetingroom', name='embedding_version'),
    ]
