# Generated by Django 4.1.5 on 2026-02-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0009_split_meeting_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='chunk_count',
            field=models.IntegerField(default=0, help_text='Number of chunks created'),
        ),
    ]
